### ISSUE TITLE
format regex

### ISSUE THREAD

**Issue by jesse1993** [cmur2/language-fluentd#1]
![image](https://user-images.githubusercontent.com/32831775/36134618-e5e2c638-10c0-11e8-8d7f-1346ab640a67.png)

**Comment by cmur2** [comment]
This should be fixed for common cases in the newest release via https://github.com/cmur2/language-fluentd/commit/da21bc01ccd896af75ed1c1a63e10457ce714196. Just try updating the package to `1.1.2`.
